USE [db_a41d58_asistencia]
GO
/****** Object:  Table [dbo].[Vacaciones]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[Vacaciones] ([IdEmpresa], [IdVacaciones], [IdEmpleado], [FechaInicio], [FechaFin], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 1, 1, CAST(0x0000966C00000000 AS DateTime), CAST(0x0000966C00000000 AS DateTime), 1, 1, CAST(0x0000966C00000000 AS DateTime), NULL, NULL)
/****** Object:  Table [dbo].[Rol]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[Rol] ([IdEmpresa], [IdRol], [Rol], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 1, N'Administrador', 1, 1, CAST(0x0000A7B400000000 AS DateTime), NULL, NULL)
INSERT [dbo].[Rol] ([IdEmpresa], [IdRol], [Rol], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 2, N'Operador', 1, 1, CAST(0x0000A7B400000000 AS DateTime), NULL, NULL)
INSERT [dbo].[Rol] ([IdEmpresa], [IdRol], [Rol], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 3, N'Contabilidad', 1, 1, CAST(0x0000A7B400000000 AS DateTime), NULL, NULL)
/****** Object:  Table [dbo].[Area]    Script Date: 06/09/2022 20:14:34 ******/
SET IDENTITY_INSERT [dbo].[Area] ON
INSERT [dbo].[Area] ([IdArea], [NombreArea], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, N'VENTAS', 1, NULL, NULL, NULL, NULL)
INSERT [dbo].[Area] ([IdArea], [NombreArea], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (2, N'SISTEMAS', 1, NULL, NULL, NULL, NULL)
INSERT [dbo].[Area] ([IdArea], [NombreArea], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (3, N'LOGISTICA', 1, NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Area] OFF
/****** Object:  Table [dbo].[TablaMaestra]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 0, N'', N'TIPO DOCUMENTO IDENTIDAD', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 1, N'', N'DNI', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 2, N'', N'LIBRETA MILITAR', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 3, N'', N'PARTIDA DE NACIMIENTO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (2, 0, N'', N'ESTADO CIVIL', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (2, 1, N'', N'SOLTERO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (2, 2, N'', N'CASADO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (2, 3, N'', N'VIUDO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (2, 4, N'', N'DIVORCIADO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (3, 0, N'', N'ESTADO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (3, 1, N'1', N'ACTIVO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (3, 2, N'0', N'INACTIVO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (4, 0, N'', N'TIPO HORARIO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (4, 1, N'', N'FIJO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (4, 2, N'', N'VARIABLE', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (5, 0, N'', N'SEXO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (5, 1, N'1', N'MASCULINO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
INSERT [dbo].[TablaMaestra] ([IdTabla], [IdColumna], [Valor], [Descripcion], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (5, 2, N'0', N'FEMENINO', 1, 1, CAST(0x0000A6EB012814E0 AS DateTime), NULL, NULL)
/****** Object:  Table [dbo].[Horario]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[Horario] ([IdEmpresa], [IdHorario], [Horario], [Descripcion], [IdTipoHorario], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 1, N'HORARIO "PRODUCCION"', N'07:00 - 16:30', 1, 1, 1, CAST(0x0000A7AF0131F820 AS DateTime), NULL, NULL)
/****** Object:  Table [dbo].[Menu]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 1, N'', N'Sistema de Marcaciones', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 2, N'01', N'Gestión de Empleados', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 3, N'0101', N'Empleados', N'/empleado/list', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 4, N'02', N'Control de Asistencia', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 5, N'0201', N'Vacaciones', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 6, N'0202', N'Horarios', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 7, N'0203', N'Asignación de Horarios', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 8, N'0204', N'Permisos', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 9, N'0205', N'Gestión de Marcaciones', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 10, N'03', N'Catálogo', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 11, N'0301', N'Gestión de Tipo Documento', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 12, N'0302', N'Gestión de Tabla Maestra', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 13, N'04', N'Reportes', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 14, N'05', N'Seguridad', N'', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 15, N'0501', N'Usuario', N' ', 1)
INSERT [dbo].[Menu] ([IdEmpresa], [IdMenu], [CodMenu], [Menu], [Controller], [FlagActivo]) VALUES (1, 16, N'0502', N'Rol', N' ', 1)
/****** Object:  Table [dbo].[Marcacion]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[Marcacion] ([IdEmpresa], [IdMarcacion], [IdEmpleado], [IdHorario], [FechaMarcacion], [HoraTrabajoInicio], [HoraRefrigerioInicio], [HoraRefrigerioFin], [HoraTrabajoFin], [HorasTrabajadas], [HorasRefrigerio], [HorasTardanza], [HorasExtra]) VALUES (1, 1, 1, 1, CAST(0x0000A7AF00000000 AS DateTime), CAST(0x0000A7AF00000000 AS DateTime), CAST(0x0000A7AF00000000 AS DateTime), CAST(0x0000A7AF00000000 AS DateTime), CAST(0x0000A7AF00000000 AS DateTime), CAST(0.0000 AS Decimal(18, 4)), CAST(0.0000 AS Decimal(18, 4)), CAST(0.0000 AS Decimal(18, 4)), CAST(0.0000 AS Decimal(18, 4)))
/****** Object:  Table [dbo].[HorarioDetalle]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[HorarioDetalle] ([IdEmpresa], [IdHorarioDetalle], [IdHorario], [Dia], [HoraTrabajoInicio], [HoraTrabajoFin], [HoraRefrigerioInicio], [HoraRefrigerioFin], [NroMinutosToleranciaEntrada], [NroMinutosToleranciaRefrigerio], [FlagNocturno], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 1, 1, 1, CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), 0, 0, 0, 1, 1, CAST(0x0000000000735B40 AS DateTime), NULL, NULL)
INSERT [dbo].[HorarioDetalle] ([IdEmpresa], [IdHorarioDetalle], [IdHorario], [Dia], [HoraTrabajoInicio], [HoraTrabajoFin], [HoraRefrigerioInicio], [HoraRefrigerioFin], [NroMinutosToleranciaEntrada], [NroMinutosToleranciaRefrigerio], [FlagNocturno], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 2, 1, 2, CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), 0, 0, 0, 1, 1, CAST(0x0000000000735B40 AS DateTime), NULL, NULL)
INSERT [dbo].[HorarioDetalle] ([IdEmpresa], [IdHorarioDetalle], [IdHorario], [Dia], [HoraTrabajoInicio], [HoraTrabajoFin], [HoraRefrigerioInicio], [HoraRefrigerioFin], [NroMinutosToleranciaEntrada], [NroMinutosToleranciaRefrigerio], [FlagNocturno], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 3, 1, 3, CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), 0, 0, 0, 1, 1, CAST(0x0000000000735B40 AS DateTime), NULL, NULL)
INSERT [dbo].[HorarioDetalle] ([IdEmpresa], [IdHorarioDetalle], [IdHorario], [Dia], [HoraTrabajoInicio], [HoraTrabajoFin], [HoraRefrigerioInicio], [HoraRefrigerioFin], [NroMinutosToleranciaEntrada], [NroMinutosToleranciaRefrigerio], [FlagNocturno], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 4, 1, 4, CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), 0, 0, 0, 1, 1, CAST(0x0000000000735B40 AS DateTime), NULL, NULL)
INSERT [dbo].[HorarioDetalle] ([IdEmpresa], [IdHorarioDetalle], [IdHorario], [Dia], [HoraTrabajoInicio], [HoraTrabajoFin], [HoraRefrigerioInicio], [HoraRefrigerioFin], [NroMinutosToleranciaEntrada], [NroMinutosToleranciaRefrigerio], [FlagNocturno], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 5, 1, 5, CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), 0, 0, 0, 1, 1, CAST(0x0000000000735B40 AS DateTime), NULL, NULL)
INSERT [dbo].[HorarioDetalle] ([IdEmpresa], [IdHorarioDetalle], [IdHorario], [Dia], [HoraTrabajoInicio], [HoraTrabajoFin], [HoraRefrigerioInicio], [HoraRefrigerioFin], [NroMinutosToleranciaEntrada], [NroMinutosToleranciaRefrigerio], [FlagNocturno], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 6, 1, 6, CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), 0, 0, 0, 1, 1, CAST(0x0000000000735B40 AS DateTime), NULL, NULL)
INSERT [dbo].[HorarioDetalle] ([IdEmpresa], [IdHorarioDetalle], [IdHorario], [Dia], [HoraTrabajoInicio], [HoraTrabajoFin], [HoraRefrigerioInicio], [HoraRefrigerioFin], [NroMinutosToleranciaEntrada], [NroMinutosToleranciaRefrigerio], [FlagNocturno], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 7, 1, 7, CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), CAST(0x0000000000735B40 AS DateTime), 0, 0, 0, 1, 1, CAST(0x0000000000735B40 AS DateTime), NULL, NULL)
/****** Object:  Table [dbo].[EmpleadoHorario]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[EmpleadoHorario] ([IdEmpresa], [IdEmpleadoHorario], [IdEmpleado], [IdHorario], [FechaInicio], [FechaFin], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 1, 1, 1, CAST(0x0000A7AF00000000 AS DateTime), NULL, 1, 1, CAST(0x0000A7AF00000000 AS DateTime), NULL, NULL)
/****** Object:  Table [dbo].[Empleado]    Script Date: 06/09/2022 20:14:34 ******/
SET IDENTITY_INSERT [dbo].[Empleado] ON
INSERT [dbo].[Empleado] ([IdEmpresa], [IdEmpleado], [CodigoMarcacion], [ApellidoPaterno], [ApellidoMaterno], [Nombres], [Sexo], [IdTipoDocIdentidad], [NroDocIdentidad], [FechaNacimiento], [FechaIngreso], [Email], [Direccion], [Telefono], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion], [IdArea]) VALUES (1, 1, N'41344776', N'DIAZ', N'MANTILLA', N'FRANCISCO ALBERTO', N'M', N'DNI', N'41344776', CAST(0x00009B8100000000 AS DateTime), CAST(0x0000A51C00000000 AS DateTime), N'pruebas@gmail.com', N'Los Alamos', N'987678987', 1, 1, CAST(0x0000A51C00000000 AS DateTime), 1, CAST(0x0000AEAF00000000 AS DateTime), 2)
INSERT [dbo].[Empleado] ([IdEmpresa], [IdEmpleado], [CodigoMarcacion], [ApellidoPaterno], [ApellidoMaterno], [Nombres], [Sexo], [IdTipoDocIdentidad], [NroDocIdentidad], [FechaNacimiento], [FechaIngreso], [Email], [Direccion], [Telefono], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion], [IdArea]) VALUES (1, 6, N'70032987', N'SANTIAGO', N'YAURICASA', N'CARELY', N'F', N'DNI', N'70032987', CAST(0x00008CE800000000 AS DateTime), CAST(0x0000A9C800000000 AS DateTime), N'edirlewa@hotmail.com', N'Los Sauces', N'987456983', 1, 1, CAST(0x0000AEAF00000000 AS DateTime), 1, CAST(0x0000AEAF00000000 AS DateTime), NULL)
INSERT [dbo].[Empleado] ([IdEmpresa], [IdEmpleado], [CodigoMarcacion], [ApellidoPaterno], [ApellidoMaterno], [Nombres], [Sexo], [IdTipoDocIdentidad], [NroDocIdentidad], [FechaNacimiento], [FechaIngreso], [Email], [Direccion], [Telefono], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion], [IdArea]) VALUES (1, 9, N'70032986', N'ESPINOZA', N'GARCIA', N'JOSE', N'M', N'DNI', N'70032986', CAST(0x0000836100000000 AS DateTime), CAST(0x0000AB5700000000 AS DateTime), N'pablocettu@hotmail.com', N'Los Sauces #456', N'987456956', 1, 1, CAST(0x0000AEAF00000000 AS DateTime), NULL, NULL, 1)
SET IDENTITY_INSERT [dbo].[Empleado] OFF
/****** Object:  Table [dbo].[RolMenu]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 1)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 2)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 3)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 4)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 5)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 6)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 7)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 8)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 9)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 10)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 11)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 12)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 13)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 14)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 15)
INSERT [dbo].[RolMenu] ([IdEmpresa], [IdRol], [IdMenu]) VALUES (1, 1, 16)
/****** Object:  Table [dbo].[Usuario]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[Usuario] ([IdEmpresa], [IdUsuario], [IdRol], [ApellidoPaterno], [ApellidoMaterno], [Nombres], [Usuario], [Clave], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 1, 1, N'VEGA', N'ROSALES', N'JUAN', N'ADMIN', N'12345678', 1, 1, CAST(0x0000A6F900000000 AS DateTime), NULL, NULL)
INSERT [dbo].[Usuario] ([IdEmpresa], [IdUsuario], [IdRol], [ApellidoPaterno], [ApellidoMaterno], [Nombres], [Usuario], [Clave], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 2, 2, N'QUISPE', N'FLORES', N'ROBERTO', N'OPERADOR1', N'12345', 1, 1, CAST(0x0000A6F900000000 AS DateTime), NULL, NULL)
/****** Object:  Table [dbo].[UsuarioMenu]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 1)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 2)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 3)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 4)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 5)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 6)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 7)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 8)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 9)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 10)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 11)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 12)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 13)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 14)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 15)
INSERT [dbo].[UsuarioMenu] ([IdEmpresa], [IdUsuario], [IdMenu]) VALUES (1, 1, 16)
/****** Object:  Table [dbo].[Permiso]    Script Date: 06/09/2022 20:14:34 ******/
INSERT [dbo].[Permiso] ([IdEmpresa], [IdPermiso], [IdEmpleado], [Motivo], [Observacion], [FechaInicio], [FechaFin], [FlagActivo], [IdUsuarioCreacion], [FechaCreacion], [IdUsuarioModificacion], [FechaModificacion]) VALUES (1, 1, 1, N'', N'', CAST(0x0000A7B400000000 AS DateTime), CAST(0x0000A7B400000000 AS DateTime), 1, 1, CAST(0x0000A7B400000000 AS DateTime), NULL, NULL)
